abstract class AppData {
  static const List<String> foodCategories = [
    'Appetizers',
    'Soups',
    'Salads',
    'Sandwiches',
    'Burgers',
    'Pizza',
    'Pasta',
    'Rice Dishes',
    'Noodles',
    'Seafood',
    'Steak',
    'Barbecue',
    'Grilled',
    'Fried Food',
    'Roasted',
    'Stews',
    'Curries',
    'Vegetarian',
    'Vegan',
    'Gluten-Free',
    'Sushi',
    'Dim Sum',
    'Tacos',
    'Burritos',
    'Wraps',
    'Kebabs',
    'Shawarma',
    'Falafel',
    'Dumplings',
    'Casseroles',
    'Breakfast',
    'Brunch',
    'Lunch',
    'Dinner',
    'Snacks',
    'Street Food',
    'Desserts',
    'Cakes',
    'Pastries',
    'Ice Cream',
    'Pies',
    'Cookies',
    'Chocolates',
    'Puddings',
    'Fruit',
    'Smoothies',
    'Juices',
    'Drinks',
    'Coffee',
    'Tea',
    'Milkshakes',
    'Energy Drinks',
    'Hot Drinks',
    'Cold Drinks',
    'Salami',
    'Sausages',
    'Cheese',
    'Tapas',
    'Mezze',
    'Samosas',
    'Spring Rolls',
    'Tempura',
    'Ramen',
    'Pho',
    'Gyoza',
    'Paella',
    'Risotto',
    'Lasagna',
    'Quiche',
    'Omelette',
    'Pancakes',
    'Waffles',
    'Crepes',
    'Bagels',
    'Muffins',
    'Donuts',
    'Brownies',
    'Souffle',
    'Tarts',
    'Mousse',
    'Yogurt',
    'Granola',
    'Cereal',
    'Porridge',
    'Hot Dogs',
    'Chicken Wings',
    'Meatballs',
    'Fish & Chips',
    'Tortillas',
    'Nachos',
    'Popcorn',
    'Nuggets',
    'Onion Rings',
    'Potato Chips',
    'French Fries',
    'Mashed Potatoes',
    'Coleslaw',
    'Pickles',
    'Relish',
    'Sauces',
    'Dips',
  ];

  static const List<String> restaurantTypes = [
    'cafe',
    'restaurant',
    'fastFood',
    'breakfast',
  ];

  static const List<String> weekDays = [
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
    'Sunday',
  ];

  static List<String> dayTimes = [
    for (var hour = 0; hour < 24; hour++) ...[
      '${hour.toString().padLeft(2, '0')}:00',
      '${hour.toString().padLeft(2, '0')}:30',
    ],
  ];
}
